### ISSUE TITLE
randomsample implementation

### ISSUE THREAD

**Issue by dynaryu** [jieunbyun/BNS-JT#6]
In the singleSample.m 
```
    if ( sampleInd == 1 ) && ( sum( cpmToSample.p ) ~= 1 )
        warning( 'Given probability vector does not sum to 1' )
    end
```
Can I just ignore this warning? 
BTW, I don't have the statistics toolbox.
If cpmToSample.p is [0.99, 0.01, 0.9, 0.1], then what should be the probability vector for random sampling? 
It looks like it is re-evalued as [0.99, 0.01, 0.9, 0.1]/sum of the vector.

**Comment by jieunbyun** [comment]
I would rather keep it. It is a common mistake that a user put wrong numbers in a probability vector, and one of the smoking guns is that the probability vector does not sum up to 1. So I personally find the warning message quite useful to detect errors in input data.

**Comment by dynaryu** [comment]
What about the probability vector? Do I understand correctly?

**Comment by dynaryu** [comment]
And what would be the expected outcome of singleSample.m given the input? 
I'd like to check if the function is working properly or not.
Can you share the output as I don't have the statistics toolbox.

**Comment by jieunbyun** [comment]
As of the probability vector, if a random variable has a probability vector [0.99, 0.01, 0.9, 0.1], it would have an event matrix, for example, [1 1; 2 1; 2 1; 2 2] with the second column standing for a parent node’s states.
Then, since all parent nodes must have been sampled before the random variable being sampled, when it comes to sampling this random variable, its parent node must have been already sampled to either State 1 or 2, which would then make the probability vector either [0.99, 0.01] or [0.9, 0.1], respectively.
This is why there is an error message (in Line 46) “error( 'Given CPMs include undefined parent nodes' )”, which prevents MCS from going forward if there is any parent node that has not been sampled.

**Comment by jieunbyun** [comment]
I revised the function to use “rand” instead of “randsample”. Now the function should run without Statistics Toolbox.
Just let me know if the issue persists.
