### ISSUE TITLE
output of fnTrans.doBranch

### ISSUE THREAD

**Issue by dynaryu** [jieunbyun/BNS-JT#9]
For node 5 to 1 
```        
Input:
arc_paths = [[2], [1, 3]]
path_times = [0.0901, 0.2401]
unfinished = 0

Output:
branches_surv = [[2], [1, 3], [1], []]
branches_fail = [[], [2], [2, 3], [1, 2]]
states = [1, 2, 3, 3]
times = [0.0901, 0.2401, 100, 100]
```
Why state of the second case (arc [1, 3] survival, arc [2] failure) becomes 2 not 1? 
What does 1, 2, and 3 mean as a system for this case?

**Comment by jieunbyun** [comment]
Because the states are defined by the travel time, and it takes different times to travel by arc 2 and by arc 1 & 3.
The array “times” illustrates the corresponding travel times to each state.

From: Hyeuk Ryu ***@***.***>
Sent: 31 March 2023 11:41
To: jieunbyun/BNS-JT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jieunbyun/BNS-JT] output of fnTrans.doBranch (Issue #9)


For node 5 to 1

Input:

arc_paths = [[2], [1, 3]]

path_times = [0.0901, 0.2401]

unfinished = 0



Output:

branches_surv = [[2], [1, 3], [1], []]

branches_fail = [[], [2], [2, 3], [1, 2]]

states = [1, 2, 3, 3]

times = [0.0901, 0.2401, 100, 100]

Why state of the second case (arc [1, 3] survival, arc [2] failure) becomes 2 not 1?
What does 1, 2, and 3 mean as a system for this case?

**Comment by dynaryu** [comment]
What I said last night was some potential issue due to too many states from continuous variable. 
Alternative approach is binning which converts continous variable to categorical one.

**Comment by jieunbyun** [comment]
Thanks, I will keep that in mind and think over.
